[build]
  command = "quasar build -m pwa"
  publish = "dist/pwa"  # Isso garante que a versão PWA seja publicada

[[headers]]
  for = "/*"
  [headers.values]
    # Garante que o conteúdo seja servido por HTTPS
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Permite o uso de service workers em PWA
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
